# Generated by Django 4.1.3 on 2022-11-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='course',
            new_name='course_title',
        ),
    ]
